version: 3
endpoint: http://localhost:8081
admin_secret: hunter1
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://host.docker.internal:3000/hasura-auth
# This file is used LOCALLY by hasura-cli. The Dockerfile does not use this, and neither does docker-compose.ynl
