version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    #network_mode: "host" # Uncomment this on Linux!
    ports:
      - "8081:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres # Mac, Win
      #HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres # Linux
      HASURA_GRAPHQL_AUTH_HOOK: "http://host.docker.internal:3000/hasura-auth" # Mac, Win
      #HASURA_GRAPHQL_AUTH_HOOK: "http://localhost:3000/hasura-auth" # Linux
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # Use `hasura console` instead, otherwise migrations won't work.
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup,webhook-log,http-log"
      HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT: 60
      HASURA_GRAPHQL_ADMIN_SECRET: "hunter1"
